apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sehyoun-team-app-guestbook
  namespace: argocd
spec:
  project: sehyoun-team-project
  source:
    repoURL: https://github.com/lyutvs/Study-management.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: sehyoun-team-ns
  syncPolicy:
    syncOptions:
      - CreateNamespace=true